#!/bin/sh

roles="aide alternatives anaconda ansible ansible_lint apt_autostart apt_repository artifactory at auditd auto_update autofs awx_configuration azure_cli backup bios_update bootstrap buildtools ca ca_certificates cargo certbot cis clamav cntlm code collabora_online collectd common consul container_docs core_dependencies cron cups cve_2018_19788 cve_2021_44228 debug dhcpd digitalocean diskspace dns dnsmasq docker docker_ce docker_compose dovecot dryrun dsvpn earlyoom eclipse elastic_repo elasticsearch environment epel etherpad f5_ltm facts fail2ban filesystem firewall forensics functions git gitea gitlab gitlab_runner glusterfs gnome gotop grub haproxy harbor hashicorp haveged hostname httpd investigate irslackd java jenkins jitsi keepalived kernel kibana kubectl libvirt locale logrotate logstash logwatch luks lvm lynis maintenance mate mediawiki memcached metricbeat microsoft_repository_keys minikube mitogen modprobe molecule moodle mount mssql mysql natrouter nextcloud nfsserver nginx node_red nomad npm ntp obsproject openssh openssl openvpn owncloud packer php php_fpm phpmyadmin podman postfix postgres powertools powertop python_pip qemu rabbitvcs reboot redis remi restore revealmd roundcubemail rpmfusion rsyslog ruby rundeck scl selinux service snmpd software sosreport spamassassin squid storage stratis subversion sudo swap sysctl sysstat systemd terraform test_connection tftpd tigervnc tlp tomcat tune2fs turn types ulimit umask unbound unowned_files update update_package_cache update_pip_packages upgrade users vagrant vault vdo virtualbox xinetd xrdp zabbix_agent zabbix_proxy zabbix_repository zabbix_server zabbix_web"


echo "|Role name|GitHub Action|GitLab CI|Version|"
echo "|---------|-------------|---------|-------|"

for role in ${roles} ; do
  echo "|[${role}](https://galaxy.ansible.com/robertdebock/${role})|[![github](https://github.com/robertdebock/ansible-role-${role}/workflows/Ansible%20Molecule/badge.svg)](https://github.com/robertdebock/ansible-role-${role}/actions)|[![gitlab](https://gitlab.com/robertdebock-iac/ansible-role-${role}/badges/master/pipeline.svg)](https://gitlab.com/robertdebock-iac/ansible-role-${role}/-/pipelines)|[![version](https://img.shields.io/github/commits-since/robertdebock/ansible-role-${role}/latest.svg)](https://github.com/robertdebock/ansible-role-${role}/releases)|"
done
