#!/usr/bin/env ansible-playbook
---
- name: generate molecule.yml
  hosts: localhost
  become: no
  gather_facts: no

  tasks:
    - name: set role_path and role_name
      set_fact:
        role_path: "{{ lookup('env', 'PWD') }}"
        role_name: "{{ lookup('env', 'PWD') | basename | regex_replace('ansible-role-') }}"

    - name: see if molecule/default/verify.yml exists
      stat:
        path: "{{ role_path }}/molecule/default/verify.yml"
      register: verify

    - name: generate generic molecule.yml
      template:
        src: "molecule.yml.j2"
        dest: "{{ role_path }}/molecule/default/molecule.yml"
