#!/usr/bin/env ansible-playbook
---
- name: generate a README.md, github/settings.yml and LICENSE for roles
  hosts: localhost
  become: no
  gather_facts: yes

  tasks:
    - name: set role_path and role_name
      set_fact:
        role_path: "{{ pwd }}"
        role_name: "{{ pwd | basename | regex_replace('ansible-role-') }}"

    - name: load meta
      include_vars:
        file: "{{ role_path }}/meta/main.yml"
        name: meta

    - name: load defaults/main.yml
      slurp:
        src: "{{ role_path }}/defaults/main.yml"
      register: variables

    - name: check if requirements.yml exists
      stat:
        path: "{{ role_path }}/requirements.yml"
      register: check_requirements

    - name: load requirements
      slurp:
        src: "{{ role_path }}/requirements.yml"
      register: requirements
      when:
        - check_requirements.stat.exists

    - name: set no requirements when none exist
      set_fact:
        requirements:
          content: "{{ '- none' | b64encode }}"
      when:
        - not check_requirements.stat.exists

    - name: load compatibility
      command: "{{ playbook_dir }}/compatibility.sh"
      args:
        chdir: "{{ role_path }}"
      register: compatibility
      changed_when: no

    - name: load example
      slurp:
        src: "{{ role_path }}/molecule/resources/playbook.yml"
      register: example

    - name: check if prepare.yml exists
      stat:
        path: "{{ role_path }}/molecule/resources/prepare.yml"
      register: check_prepare

    - name: load prepare
      slurp:
        src: "{{ role_path }}/molecule/resources/prepare.yml"
      register: prepare
      when:
        - "{{ check_prepare.stat.exists }}"

    - name: render template
      template:
        src: "{{ playbook_dir }}/templates/README.md.j2"
        dest: "{{ role_path }}/README.md"

    - name: create .github
      file:
        path: "{{ role_path }}/.github"
        state: directory

    - name: render .github/settings.yml
      template:
        src: "{{ playbook_dir }}/templates/settings.yml.j2"
        dest: "{{ role_path }}/.github/settings.yml"

    - name: set author variables
      set_fact:
        author: Robert de Bock (robert@meinit.nl)

    - name: render LICENSE
      template:
        src: "{{ playbook_dir }}/templates/LICENSE-2.0.txt.j2"
        dest: "{{ role_path }}/LICENSE"
